### PR TITLE
Update response parsing

### PR DESCRIPTION
**Pull request by emctackett**
@BaffourAdu 

This code generates a new download url (based on version number) and stores it in the `outdatedpackages` generated file.  The code doesn't generate a new checksum yet.  I tried to use the code we talked about a few minutes ago, but was running into an error-- `300 Multiple Choices (OpenURI::HTTPError)` when attempting to generate the new 

I removed the breaking checksum code for now, but will keep trying to resolve this issue.

### CODE REVIEW

**Comment by BaffourAdu** [comment]
@emctackett great job! Do you want me to merge this in and then submit the code for the checksum as a separate PR?

**Comment by emctackett** [comment]
@BaffourAdu I went ahead and pushed up a commit w/the checksum code so you can take a look at it.  I cannot get it working, although it should operate just as the example code we were looking at. 

The method is called `generate_checksum`.  Line 15 of `compareHomeBrewAndRepology.rb`.  To test it, you'll need to add an invocation somewhere.

I will keep working on it.. let me know if you have any ideas or success.

**Comment by emctackett** [comment]
I think the problem is that an error is thrown when the `new_download_url` is invalid.  Unfortunately, I think this is quite a lot of them.

As an example, `generate_checksum` seems to work just fine when `"https://github.com/witten/borgmatic/archive/1.5.6.tar.gz"` is passed in (this is a valid download url).

**Comment by BaffourAdu** [comment]
@emctackett this makes sense, so then what I would suggest before you run `generate_checksum` you will need to validate the download URL.

**Comment by johndbritton** [comment]
I removed myself as a reviewer, when you’re ready for a review you can add me again and leave a comment on what you want feedback on.

**Comment by emctackett** [comment]
@BaffourAdu In this latest update, I added exception handling to `generate_checksum`.  In the case that a url is invalid, `generate_checksum` will return `nil`.

packages with a checksum of `nil` are then not added to the `txt` file generated by `compareHomeBrewAndRepology.rb`, since we don't have the proper information to update them anyway.

**Comment by larson-carter** [comment]
@johndbritton That was my fault, I accidentally clicked your name when trying to add people to this review list.

**Comment by johndbritton** [comment]
> @johndbritton That was my fault, I accidentally clicked your name when trying to add people to this review list.

Not a problem. Happy to review things in the if you want my feedback. Just be sure to specify what feedback you want.

**Comment by BaffourAdu** [comment]
@emctackett Nice job! I would suggest you save all the ones with a checksum of nil to a separate txt file so we can have a script parse through them to regenerate them later.

**Pull request merged**
